#!/usr/bin/env python3
"""Build the manuals shards from the manifest.

_data/manuals.json is the source of truth: one row per official RV manual
library or document, each one observed on the maker's own site. This script
validates that manifest and writes the per-system shards the manuals pages
load, so a page ships only its own slice of the corpus.

Two things it refuses to do, on purpose:

  * let a row claim a document URL is stable when the URL carries a revision
    token, a date, or a dated upload folder. Those links die silently the
    moment the maker publishes a new revision. Measured across real URLs,
    not guessed (research round 2-A).
  * let a banned host into the corpus. Aggregators, mirrors and retailers are
    discovery only, never a link.

The site-wide search bundle is deliberately NOT written here. The whole corpus
is far too heavy to put in front of every visitor, so the search head set is a
separate capped file and lands with the search wiring.

Run: python3 scripts/build-manuals.py            validate, sanitize, write shards
     python3 scripts/build-manuals.py --check    validate only, no writes
"""
import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import manuals_rules as R  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "_data/manuals.json"
OUTDIR = ROOT / "assets/js/manuals"


def write_shards(by_system):
    OUTDIR.mkdir(parents=True, exist_ok=True)
    written = []
    for slug, title in R.SYSTEMS:
        rows = by_system.get(slug, [])
        body = json.dumps(rows, ensure_ascii=False, separators=(",", ":"))
        var = "RV_MANUALS_" + slug.upper().replace("-", "_")
        text = (
            "/* Generated by scripts/build-manuals.py. Do not hand-edit.\n"
            "   %s. Fields: brand, host the library that serves the file, system,\n"
            "   kind document|library, doc_types, title, url, key what the document\n"
            "   is keyed to, covers what it covers, rev revision stamp when the\n"
            "   document carries one, gate none|free-account|paid, link_stability,\n"
            "   checked, and note for an optional caveat about the link itself.\n"
            "   LINKS ONLY: every url is the maker's own copy. We never mirror a\n"
            "   document, and a row ships only once the link resolves AND the\n"
            "   document names the model it is filed under. */\n"
            "window.%s = %s;\n" % (title, var, body))
        path = OUTDIR / ("%s.js" % slug)
        path.write_text(text, encoding="utf-8")
        written.append((path, len(rows), len(text.encode("utf-8"))))
    return written


def main():
    doc, error = R.load(MANIFEST)
    if error:
        print("FAIL  %s: %s" % (MANIFEST.relative_to(ROOT), error))
        raise SystemExit(1)

    errors = []
    dashes = 0
    components, n = R.clean_dashes(doc.get("components", []))
    dashes += n
    brands, n = R.clean_dashes(doc.get("brands", []))
    dashes += n
    models, n = R.clean_dashes(doc.get("models", []))
    dashes += n

    if not components:
        errors.append("components is empty")
    if not brands:
        errors.append("brands is empty")
    if not models:
        errors.append("models is empty")

    R.check_components(components, errors)
    R.check_brands(brands, errors)
    R.check_models(models, errors)

    if errors:
        print("=== manifest problems (%d) ===" % len(errors))
        for e in errors[:40]:
            print("  FAIL " + e)
        if len(errors) > 40:
            print("  ... and %d more" % (len(errors) - 40))
        raise SystemExit(1)

    by_system = {}
    for r in components:
        by_system.setdefault(r["system"], []).append(r)

    print("=" * 88)
    print("MANUALS MANIFEST")
    print("=" * 88)
    print("  %d component rows, %d brand rows, %d unique component brands\n"
          % (len(components), len(brands), len({r["brand"] for r in components})))

    print("  rows per system")
    for slug, title in R.SYSTEMS:
        print("    %-26s %3d" % (title, len(by_system.get(slug, []))))

    print("\n  rows per document type")
    dt = Counter(t for r in components for t in r["doc_types"])
    for t in R.DOC_TYPES:
        print("    %-22s %3d" % (t, dt.get(t, 0)))

    print("\n  kind      %s" % dict(Counter(r["kind"] for r in components)))
    print("  gate      %s" % dict(Counter(r["gate"] for r in components)))
    print("  stability %s" % dict(Counter(r["link_stability"] for r in components)))
    st = Counter(r.get("status", "never checked") for r in components)
    print("  status    %s" % dict(st))
    if st.get("never checked"):
        print("            %d rows have not been through a live audit yet"
              % st["never checked"])

    # The model axis. Counted here rather than on a page, so "how many models do
    # we carry" is answered from the data instead of from a sentence.
    print("\n  %d model rows across %d makes" % (len(models),
                                                 len({r["brand"] for r in models})))
    mseg = Counter(s for r in models for s in r["segments"])
    for s in R.SEGMENTS:
        if mseg.get(s):
            print("    %-18s %3d" % (s, mseg[s]))
    print("  no segment stated  %3d" % sum(1 for r in models if not r["segments"]))
    print("  parts channel      %3d of %d" % (sum(1 for r in models if r["parts_url"]),
                                              len(models)))
    print("  accessory catalog  %3d of %d" % (sum(1 for r in models if r["accessories_url"]),
                                              len(models)))
    print("  no manual url      %3d" % sum(1 for r in models if not r["url"]))

    if dashes:
        print("\n  rule #11: %d banned dash characters replaced" % dashes)

    if "--check" in sys.argv:
        print("\nVALID (no files written)")
        return

    written = write_shards(by_system)
    print("\n  shards written to assets/js/manuals/")
    for path, count, size in written:
        print("    %-34s %3d rows %7.1f KB" % (path.name, count, size / 1024.0))
    print("    %-34s %17.1f KB" % ("TOTAL", sum(s for _, _, s in written) / 1024.0))

    # One combined file so the hub's own search can reach the whole corpus. The
    # hub does not load this with the page: it waits for the first keystroke, so
    # a visitor who only wants the tiles never pays for it.
    #
    # This used to carry the component corpus alone, which meant the hub search
    # could not find ANY of the 44 makers listed on its own brand page: typing
    # "Jayco" returned "Nothing matches that" (measured 2026-09-22). Brand and
    # model rows are carried in a LEAN shape -- what a search result needs, not
    # the provenance (evidence quotes, notes, parts blurbs) that only the audit
    # and the page generator use. The weight matters: this file is fetched on a
    # keystroke, and the full model corpus is several hundred rows.
    def lean_brand(b):
        return {"type": "brand", "brand": b["brand"], "years": b["years"],
                "note": b["note"], "gate": b["gate"], "url": b["url"],
                "status": b.get("status")}

    def lean_model(m):
        return {"type": "model", "brand": m["brand"], "model": m["model"],
                "years": m["years"], "segments": m["segments"], "gate": m["gate"],
                "has_parts": bool(m["parts_url"]), "url": m["url"],
                "status": m.get("status")}

    search_rows = (list(components) + [lean_brand(b) for b in brands]
                   + [lean_model(m) for m in models])
    allrows = json.dumps(search_rows, ensure_ascii=False, separators=(",", ":"))
    allpath = OUTDIR / "all.js"
    allpath.write_text(
        "/* Generated by scripts/build-manuals.py. Do not hand-edit.\n"
        "   Everything the manuals hub search can reach: the component corpus,\n"
        "   plus every maker and every model line. Loaded on first keystroke,\n"
        "   never with the page. The pages themselves are rendered from\n"
        "   _data/manuals.json at build time, so this file is for searching, not\n"
        "   for drawing. A row with no `type` is a component document. */\n"
        "window.RV_MANUALS_ALL = %s;\n" % allrows, encoding="utf-8")
    print("    %-34s %3d rows %7.1f KB (hub search)" %
          ("all.js", len(search_rows), allpath.stat().st_size / 1024.0))

    # What the site-wide search would carry if capped at one row per brand,
    # which is the shape the search head set will take.
    head = {}
    for r in sorted(components, key=lambda r: (r["brand"], r["kind"] != "library")):
        head.setdefault(r["brand"], r)
    head_bytes = len(json.dumps(list(head.values()), ensure_ascii=False,
                                separators=(",", ":")).encode("utf-8"))
    print("    head set at one row per brand: %d rows, %.1f KB"
          % (len(head), head_bytes / 1024.0))


if __name__ == "__main__":
    main()
